server:
  port: 8088
test:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456
  driverClassName: com.mysql.jdbc.Driver
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
datasourceA:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.60.206:3306/jzpush?useUnicode=true&characterEncoding=UTF-8
  username: sendinmuser
  password: sendinmpw